### ISSUE TITLE
Может получиться что нужно 3.333333333 рулона?

### ISSUE THREAD

**Issue by coursar** [rufattabaev/DZ2#2]
https://github.com/rufattabaev/DZ2/blob/67e2d32411b73d4add7ae6367271858f943b01d2/src/WallpaperCalculator.java#L2

**Comment by rufattabaev** [comment]
не может, т.к. использован метод ceil из класса Math, который и округляет полученное double значение до ближайшего бОльшего целого числа.

**Comment by rufattabaev** [comment]
https://github.com/rufattabaev/DZ2/blob/67e2d32411b73d4add7ae6367271858f943b01d2/src/Main.java#L16

Я думаю что не может, т.к. я использовал метод 'ceil' из класса 'Math', который и округлит возможный double до ближайшего целого значения

**Comment by rufattabaev** [comment]
Или всё-таки нужно инициализировать как int?

**Comment by coursar** [comment]
Вы можете сделать вот так:
```java
(int) Math.ceil(...)
```
