### ISSUE TITLE
Проверить ДЗ калькулятор обоев с исправлениями

### ISSUE THREAD

**Issue by rufattabaev** [rufattabaev/DZ2#3]

**Comment by coursar** [comment]
На будущее:
1. Лучше не составлять сложных выражений: `return ((roomLength + roomWidth) * 2) / wallpaperWidth / (lengthOfRoll / roomHeight);`
2. Лучше сохранять результат вывода в переменную, а уже затем подставлять в строку: `        System.out.println("Нужно приобрести " + (int) Math.ceil(WallpaperCalculator.calculateNumberOfRolls(roomLength, roomWidth, wallpaperWidth, lengthOfRoll, roomHeight)) + " рулона(-ов) обоев");`
